"$schema" = 'https://starship.rs/config-schema.json'



format = """
[](red)\
$username\
[@fajrin ](bold fg:red  bg:bright-white)\
$os\
[](blue)\
$nodejs\
$directory\
$git_branch\
$git_status\
$time\
$line_break\ 
[🐧>](bold green )\
"""


[username]
show_always = true
format = '[$user](bold  bg:red)'

[os]
format = "[ on-$name$symbol]($style)"
style = "bold  bg:blue"
disabled = false


[directory]
style = "bold cyan"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](bold fg:white )]($style)'

[line_break]
disabled = false 


[os.symbols]
AIX = "➿ "
Alpaquita = "🔔 "
AlmaLinux = "💠 "
Alpine = "🏔️ "
ALTLinux = "Ⓐ "
Amazon = "🙂 "
Android = "🤖 "
AOSC = "🐱 "
Arch = "🎗️ "
Artix = "🎗️ "
Bluefin = "🐟 "
CachyOS = "🎗️ "
CentOS = "💠 "
Debian = "🌀 "
DragonFly = "🐉 "
Elementary = "🍏 "
Emscripten = "🔗 "
EndeavourOS = "🚀 "
Fedora = "🎩 "
FreeBSD = "😈 "
Garuda = "🦅 "
Gentoo = "🗜️ "
HardenedBSD = "🛡️ "
Illumos = "🐦 "
Ios = "📱 "
InstantOS = "⏲️ "
Kali = "🐉 "
Linux = "🐧 "
Mabox = "📦 "
Macos = "🍎 "
Manjaro = "🥭 "
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = "🌿 "
NetBSD = "🚩 "
NixOS = "❄️ "
Nobara = "🎩 "
OpenBSD = "🐡 "
OpenCloudOS = "☁️ "
openEuler = "🦉 "
openSUSE = "🦎 "
OracleLinux = "🦴 "
PikaOS = "🐤 "
Pop = "🍭 "
Raspbian = "🍓 "
Redhat = "🎩 "
RedHatEnterprise = "🎩 "
RockyLinux = "💠 "
Redox = "🧪 "
Solus = "⛵ "
SUSE = "🦎 "
Ubuntu = "󰕈 "
Ultramarine = "🔷 "
Unknown = "❓ "
Uos = "🐲 "
Void = " "
Windows = "🪟 "
Zorin = "🔹 "


[bun]
format = " [$symbol]($style)"

[buf]
format = "with [$symbol]($style)"

[c]
format = " [$symbol($name)]($style)"

[cmake]
format = " [$symbol]($style)"

[cobol]
format = " [$symbol]($style)"

[cpp]
format = " [$symbol($name)]($style)"

[crystal]
format = " [$symbol]($style)"

[daml]
format = " [$symbol]($style)"

[dart]
format = " [$symbol]($style)"

[deno]
format = " [$symbol]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = ' [$symbol]($style)'

[elm]
format = ' [$symbol]($style)'

[erlang]
format = ' [$symbol]($style)'

[fennel]
format = ' [$symbol]($style)'

[fortran]
format = ' [$symbol]($style)'

[gleam]
format = ' [$symbol]($style)'

[golang]
format = ' [$symbol]($style)'

[gradle]
format = ' [$symbol]($style)'

[haskell]
format = ' [$symbol]($style)'

[haxe]
format = ' [$symbol]($style)'

[helm]
format = ' [$symbol]($style)'

[java]
format = ' [$symbol]($style)'

[julia]
format = ' [$symbol]($style)'

[kotlin]
format = ' [$symbol]($style)'

[lua]
format = ' [$symbol]($style)'

[meson]
format = ' [$symbol]($style)'

[mojo]
format = 'with [$symbol]($style)'

[nim]
format = ' [$symbol]($style)'

[nodejs]
format = ' [$symbol]($style)'
 
[ocaml]
format = ' [$symbol(\($switch_indicator$switch_name\) )]($style)'

[odin]
format = ' [$symbol]($style)'

[opa]
format = ' [$symbol]($style)'

[perl]
format = ' [$symbol]($style)'

[php]
format = ' [$symbol]($style)'

[pixi]
format = ' [$symbol($environment )]($style)'

[pulumi]
format = ' [$symbol$stack]($style)'

[purescript]
format = ' [$symbol]($style)'

[python]
format = ' [$symbol]($style)'

[quarto]
format = ' [$symbol]($style)'

[raku]
format = ' [$symbol]($style)'

[red]
format = ' [$symbol]($style)'

[rlang]
format = ' [$symbol]($style)'

[ruby]
format = ' [$symbol]($style)'

[rust]
format = ' [$symbol]($style)'

[scala]
format = ' [$symbol]($style)'

[solidity]
format = ' [$symbol]($style)'

[swift]
format = ' [$symbol]($style)'

[typst]
format = ' [$symbol]($style)'

[vagrant]
format = ' [$symbol]($style)'

[vlang]
format = ' [$symbol]($style)'

[xmake]
format = " [$symbol]($style)"

[zig]
format = ' [$symbol]($style)'
